### PR TITLE
feat: updated the template to react

### LINKED ISSUE #2: Framework: React for building our frontend solution
**Current template cannot serve our need .**
As seen at [js-starter](https://github.com/BuildForSDG/js-starter), the base template for our frontend solution is relatively without code we could work on based on the technical requirements of our project.

**A tested and trusted framework will be solid ground to start on**
React being a modern framework for developing robust and enterprise ready frontend application is a good option based on our frontend innovator's experiences.

**Merging both templates**
The current [js-starter](https://github.com/BuildForSDG/js-starter) template has a basic standard  
which must be kept if we want good code ratings, hence ensure to add the app.properties file, and confirm the  __tests__ folder and other config files are included.

### PR DESCRIPTION
**Pull request by onyijne**
BREAKING CHANGE: removed parcel as it wasn't working with ionic

## Description
using just react parcel was okay, but on adding ionic it wasn't working, so I had to install react-scripts as it's compatible with ionic.

Fixes #2 

## How Has This Been Tested?
The previous test had node set as it's testEnvironment, I have updated this to jsdom which allowed the tests to go through.

## Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [x ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by uchennaibekwe — COMMENTED** [review]
Codacy has 19 issues with the quality of [src/themes/ionic.mixins.scss](https://github.com/BuildForSDG/Phenom-Frontend/blob/e3e378a32f8fec9676d3979af8d7bb8458e98937/src/themes/ionic.mixins.scss)

**Comment by onyijne** [comment]
> Codacy has 19 issues with the quality of [src/themes/ionic.mixins.scss](https://github.com/BuildForSDG/Phenom-Frontend/blob/e3e378a32f8fec9676d3979af8d7bb8458e98937/src/themes/ionic.mixins.scss)

Okay I'll take a look and make commits this evening.

**Review by prominded — COMMENTED** [review]
What state management system are we using, react or redux?
What api library are we using, fetch or axios?
If we are using third party, then we may need to install d packages or include their entries in package.json file

**Comment by onyijne** [comment]
> What state management system are we using, react or redux?
> What api library are we using, fetch or axios?
> If we are using third party, then we may need to install d packages or include their entries in package.json file

I have added axios, we will use react for state management. You can review again.

**Comment by prominded** [comment]
Very well then

**Review by prominded — APPROVED** [review]

**Review by Aliyugambo — APPROVED** [review]

**Review by nerjib — APPROVED** [review]

**Pull request merged**
